# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: just-fmt
        name: just fmt
        description: Format Rust code automatically
        entry: just fmt
        language: system
        types: [rust]
        pass_filenames: false

  - repo: local
    hooks:
      - id: just-format-ts-sdk
        name: just format-ts-sdk
        description: Format TypeScript SDK code
        entry: just format-ts-sdk
        language: system
        types: [ts]
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "--optional-scope",
            "--types",
            "feat,fix,chore,docs,style,refactor,perf,test,build,ci",
          ]
